#!/usr/bin/env bash
##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2014 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################

TOP_DIR=$(pwd)

# Call the meta-rdk setup script.
source meta-rdk/setup-environment $1
if [ $? -ne 0 ]; then
    return 1
fi

# OPTIONAL: meta-rdk-asp for ASP components.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-asp') -eq 0 -a -d  $TOP_DIR/meta-rdk-asp ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-rdk-asp"
EOF
fi

# Add meta-cmf-bsp-emulator ONLY if meta-rdk-bsp-emulator is included in the BBLAYERS.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-bsp-emulator') -eq 1 -a \
     $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-bsp-emulator') -eq 0 -a \
     -d  $TOP_DIR/meta-cmf-bsp-emulator ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-bsp-emulator"
EOF
fi

# Add meta-cmf-qt5 only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-qt5') -eq 0 -a -d  $TOP_DIR/meta-cmf-qt5 ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-qt5"
EOF
fi

# Add meta-cmf-restricted only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-restricted') -eq 0 -a -d  $TOP_DIR/meta-cmf-restricted ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-restricted"
EOF
fi

# Add meta-cmf-broadband only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-broadband[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-broadband ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-broadband"
EOF
fi

# Add meta-cmf-broadband only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-mesh[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-mesh ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-mesh"
EOF
fi

# Add meta-cmf-video only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-video[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-video ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-video"
EOF
fi

# Add meta-cmf-video-restricted only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-video-restricted[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-video-restricted ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-video-restricted"
EOF
fi

# Add meta-cmf-camera only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-camera[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-camera ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-camera"
EOF
fi

# Add meta-cmf only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf"
EOF
fi

# Add meta-rdk-voice-sdk only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-voice-sdk') -eq 0 -a -d  $TOP_DIR/meta-rdk-voice-sdk ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-rdk-voice-sdk"
EOF
fi

# Add meta-spdxscanner only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-spdxscanner') -eq 0 -a -d  $TOP_DIR/meta-spdxscanner ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-spdxscanner"
EOF
fi

#for capturing the timestamp
CPC_CUSTOM_STAMP=`/bin/date -u +%Y%m%d%H%M%S`
echo 'CPC_CUSTOM_STAMP = "'${CPC_CUSTOM_STAMP}'"' >> conf/auto.conf
