LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

RDEPENDS_packagegroup-rdk-ccsp-broadband_remove = "webpabroadband"

RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " ccsp-epon-agent"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " ccsp-xconf"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " dcmjsonparser"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " rdm"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " memstress"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " mesh-agent"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " notify-comp"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " harvester"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " powermgr"
RDEPENDS_packagegroup-rdk-ccsp-broadband_append = " rdkgponmanager"
